### PR TITLE
feat: SDG-16 multiple build speed improvements + rollbar sourcmaps

### PR DESCRIPTION
**Pull request by bnormington**
Speed enhancements:
1. Using `npm ci` for builds if the node_modules directory is not found
2. Add a new executor based on CircleCI's cimg/node so jobs don't need to be run on Goodway build images and can be run on images that are cached.
3. Added resource_class to all executors and node based jobs so the correct image size could be picked that fully utilized all resources.
4. Added options to the test-nodejs job and command to prevent the storing of coverage reports and if enabled to tar the coverage artifacts into a single file for faster uploads.

Feature:
1. Added a set of commands to upload javascript source maps to Rollbar.

See the following PRs for usage examples:

- https://github.com/GoodwayGroup/ui-rmn-product-manager/pull/281
- https://github.com/GoodwayGroup/service-rmn-product-manager/pull/196

### CODE REVIEW

**Review by mrcrawfo — APPROVED** [review]
Code changes make sense to me, well explained what the purposes for each are (definitely should see speed enhancements from using cached cimg iinstead)

**Review by mrcrawfo — APPROVED** [review]
Code changes make sense to me, well explained what the purposes for each are (definitely should see speed enhancements from using cached cimg iinstead)

**Review by jpiepkow — APPROVED** [review]
This is great!

**Pull request merged**
